<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="SSRIVASTAVLT2" name="testNG.Sikuli_test" tests="1" failures="0" timestamp="18 Nov 2019 19:23:01 GMT" time="20.248" errors="1">
  <testcase name="runSikuli" time="20.248" classname="testNG.Sikuli_test">
    <error type="org.sikuli.script.FindFailed" message="C:/Sid_Folder/Selenium/SikuliImages/workorder.jpg: (181x34) in S(0)[0,0 1600x900] E:Y, T:3.0">
      <![CDATA[FindFailed: C:/Sid_Folder/Selenium/SikuliImages/workorder.jpg: (181x34) in S(0)[0,0 1600x900] E:Y, T:3.0
  Line 2761, in file Region.java

at org.sikuli.script.Region.wait(Region.java:2761)
at org.sikuli.script.Region.find(Region.java:2326)
at org.sikuli.script.Region.getLocationFromTarget(Region.java:3220)
at org.sikuli.script.Region.click(Region.java:3718)
at org.sikuli.script.Region.click(Region.java:3703)
at testNG.Sikuli_test.runSikuli(Sikuli_test.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runSikuli -->
</testsuite> <!-- testNG.Sikuli_test -->
