<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [Default suite]" duration-ms="13885" started-at="2019-10-29T15:09:05Z" finished-at="2019-10-29T15:09:19Z">
    <groups>
    </groups>
    <test name="Default test(failed)" duration-ms="13885" started-at="2019-10-29T15:09:05Z" finished-at="2019-10-29T15:09:19Z">
      <class name="testNG.Sikuli_test">
        <test-method status="FAIL" signature="runSikuli()[pri:0, instance:testNG.Sikuli_test@50d0686]" name="runSikuli" duration-ms="13797" started-at="2019-10-29T15:09:05Z" finished-at="2019-10-29T15:09:19Z">
          <exception class="org.sikuli.script.FindFailed">
            <message>
              <![CDATA[C:/Sid_Folder/Selenium/SikuliImages/username.jpg: (338x62) in S(0)[0,0 1920x1080] E:Y, T:3.0]]>
            </message>
            <full-stacktrace>
              <![CDATA[FindFailed: C:/Sid_Folder/Selenium/SikuliImages/username.jpg: (338x62) in S(0)[0,0 1920x1080] E:Y, T:3.0
  Line 2761, in file Region.java

at org.sikuli.script.Region.wait(Region.java:2761)
at org.sikuli.script.Region.find(Region.java:2326)
at org.sikuli.script.Region.getLocationFromTarget(Region.java:3220)
at org.sikuli.script.Region.click(Region.java:3718)
at org.sikuli.script.Region.click(Region.java:3703)
at testNG.Sikuli_test.runSikuli(Sikuli_test.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.sikuli.script.FindFailed -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runSikuli -->
      </class> <!-- testNG.Sikuli_test -->
    </test> <!-- Default test(failed) -->
  </suite> <!-- Failed suite [Default suite] -->
</testng-results>
